name: alexpark_apikeydecryptor
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#   path: ^1.8.0
  dart_des: ^1.0.0
  convert: ^3.0.0
  mysql1: ^0.19.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
