name: alexpark_videoeditor
description: An AI video editor.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  better_player: ^0.0.72
  #video_player: ^2.1.1
  dart_vlc: ^0.0.9
  os_detect: ^2.0.0
  extended_tabs: ^2.3.0
  resizable_widget: ^1.0.4
  http: ^0.13.3
  path_provider: ^2.0.2
  quiver: ^3.0.1
  path: ^1.8.0
  async: ^2.6.0
  permission_handler: ^8.1.2
  filesystem_picker: ^2.0.0-nullsafety.0
  dart_des: ^1.0.0
  convert: ^3.0.1
  #transparent_image: ^2.0.0
  flutter_colorpicker: ^0.5.0
  input_slider: ^0.2.3
  sprintf: ^6.0.0
  #animated_text_kit: ^4.2.1
  #flutter_image: ^4.0.1
  extended_image: ^4.1.0
  flutter_staggered_grid_view: ^0.4.0
  flowder: ^0.2.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  desktop_window: ^0.4.0
  flutter_launcher_icons: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "images/48/Favourites.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/48/
    - images/32/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/SourceHanSans-Regular.otf
        - asset: fonts/SourceHanSans-Medium.otf
        - asset: fonts/SourceHanSans-Bold.otf
        - asset: fonts/SourceHanSans-ExtraLight.otf
        - asset: fonts/SourceHanSans-Heavy.otf
        - asset: fonts/SourceHanSans-Light.otf
        - asset: fonts/SourceHanSans-Normal.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
